name: Post welcome comment
on:
  pull_request:
    types: [opened]
permissions:
  pull-requests: write

jobs:
  post_welcome_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the pull request
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 Welcome to the repository! Thanks for opening a pull request."
            })
